# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{phonenormalize}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Smith"]
  s.date = %q{2009-09-16}
  s.default_executable = %q{phonenormalize}
  s.description = %q{TODO}
  s.email = %q{kognate@gmail.com}
  s.executables = ["phonenormalize"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.txt"
  ]
  s.files = [
    ".gitignore",
     "GPL",
     "History.txt",
     "LICENSE",
     "Manifest.txt",
     "PhoneNormalize.gemspec",
     "README.txt",
     "Rakefile",
     "VERSION",
     "bin/phonenormalize",
     "lib/bad_phone_number.rb",
     "lib/phonenormalize.rb",
     "test/test_phonenormalize.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/kognate/phonenormalize}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{Phone normalization class}
  s.test_files = [
    "test/test_phonenormalize.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
